package com.buzhiming.model;

import java.util.Date;

public class Askquestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.user_id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.content
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.comment_count
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.create_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_askquestion.update_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.id
     *
     * @return the value of h_askquestion.id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.id
     *
     * @param id the value for h_askquestion.id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.user_id
     *
     * @return the value of h_askquestion.user_id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.user_id
     *
     * @param userId the value for h_askquestion.user_id
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.content
     *
     * @return the value of h_askquestion.content
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.content
     *
     * @param content the value for h_askquestion.content
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.comment_count
     *
     * @return the value of h_askquestion.comment_count
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.comment_count
     *
     * @param commentCount the value for h_askquestion.comment_count
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.create_time
     *
     * @return the value of h_askquestion.create_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.create_time
     *
     * @param createTime the value for h_askquestion.create_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_askquestion.update_time
     *
     * @return the value of h_askquestion.update_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_askquestion.update_time
     *
     * @param updateTime the value for h_askquestion.update_time
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}