package com.buzhiming.model;

public class Label {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_label.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_label.name
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_label.id
     *
     * @return the value of h_label.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_label.id
     *
     * @param id the value for h_label.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_label.name
     *
     * @return the value of h_label.name
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_label.name
     *
     * @param name the value for h_label.name
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}