package com.buzhiming.model;

import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.user_id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.title
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.create_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.updata_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Date updataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.comment_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.like_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.view_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_question.content
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.id
     *
     * @return the value of h_question.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.id
     *
     * @param id the value for h_question.id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.user_id
     *
     * @return the value of h_question.user_id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.user_id
     *
     * @param userId the value for h_question.user_id
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.title
     *
     * @return the value of h_question.title
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.title
     *
     * @param title the value for h_question.title
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.create_time
     *
     * @return the value of h_question.create_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.create_time
     *
     * @param createTime the value for h_question.create_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.updata_time
     *
     * @return the value of h_question.updata_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Date getUpdataTime() {
        return updataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.updata_time
     *
     * @param updataTime the value for h_question.updata_time
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setUpdataTime(Date updataTime) {
        this.updataTime = updataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.comment_count
     *
     * @return the value of h_question.comment_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.comment_count
     *
     * @param commentCount the value for h_question.comment_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.like_count
     *
     * @return the value of h_question.like_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.like_count
     *
     * @param likeCount the value for h_question.like_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.view_count
     *
     * @return the value of h_question.view_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.view_count
     *
     * @param viewCount the value for h_question.view_count
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_question.content
     *
     * @return the value of h_question.content
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_question.content
     *
     * @param content the value for h_question.content
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}