package com.buzhiming.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.account_id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.name
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.gender
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.img_url
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.password
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.email
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.token
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.description
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.create_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_user.update_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.id
     *
     * @return the value of h_user.id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.id
     *
     * @param id the value for h_user.id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.account_id
     *
     * @return the value of h_user.account_id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.account_id
     *
     * @param accountId the value for h_user.account_id
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.name
     *
     * @return the value of h_user.name
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.name
     *
     * @param name the value for h_user.name
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.gender
     *
     * @return the value of h_user.gender
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.gender
     *
     * @param gender the value for h_user.gender
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.img_url
     *
     * @return the value of h_user.img_url
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.img_url
     *
     * @param imgUrl the value for h_user.img_url
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.password
     *
     * @return the value of h_user.password
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.password
     *
     * @param password the value for h_user.password
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.email
     *
     * @return the value of h_user.email
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.email
     *
     * @param email the value for h_user.email
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.token
     *
     * @return the value of h_user.token
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.token
     *
     * @param token the value for h_user.token
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.description
     *
     * @return the value of h_user.description
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.description
     *
     * @param description the value for h_user.description
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.create_time
     *
     * @return the value of h_user.create_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.create_time
     *
     * @param createTime the value for h_user.create_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_user.update_time
     *
     * @return the value of h_user.update_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_user.update_time
     *
     * @param updateTime the value for h_user.update_time
     *
     * @mbg.generated Wed Apr 22 15:00:08 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}