package com.buzhiming.mapper;

import com.buzhiming.model.Article;
import com.buzhiming.model.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Article> selectByExampleWithBLOBsWithRowbounds(ArticleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Article> selectByExampleWithRowbounds(ArticleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    Article selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_article
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByPrimaryKey(Article record);
}