package com.buzhiming.mapper;

import com.buzhiming.model.Askquestion;
import com.buzhiming.model.AskquestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AskquestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    long countByExample(AskquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int deleteByExample(AskquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insert(Askquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insertSelective(Askquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Askquestion> selectByExampleWithRowbounds(AskquestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Askquestion> selectByExample(AskquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    Askquestion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Askquestion record, @Param("example") AskquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExample(@Param("record") Askquestion record, @Param("example") AskquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByPrimaryKeySelective(Askquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_askquestion
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByPrimaryKey(Askquestion record);
}