package com.buzhiming.mapper;

import com.buzhiming.model.LabelRelated;
import com.buzhiming.model.LabelRelatedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LabelRelatedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    long countByExample(LabelRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int deleteByExample(LabelRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int insert(LabelRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int insertSelective(LabelRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    List<LabelRelated> selectByExampleWithRowbounds(LabelRelatedExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    List<LabelRelated> selectByExample(LabelRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    LabelRelated selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") LabelRelated record, @Param("example") LabelRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int updateByExample(@Param("record") LabelRelated record, @Param("example") LabelRelatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int updateByPrimaryKeySelective(LabelRelated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_label_related
     *
     * @mbg.generated Sun May 03 22:05:49 CST 2020
     */
    int updateByPrimaryKey(LabelRelated record);
}