package com.buzhiming.mapper;

import com.buzhiming.model.Like;
import com.buzhiming.model.LikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    long countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Like> selectByExampleWithRowbounds(LikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_like
     *
     * @mbg.generated Fri Jun 05 20:18:38 CST 2020
     */
    int updateByExample(@Param("record") Like record, @Param("example") LikeExample example);
}